using System.Collections.Generic;
using System.Xml.Serialization;
using System.Linq;

namespace FR_PRF_Parser
{
    public class Variable
    {
        [XmlIgnore]
        public uint Address;

        [XmlElement(ElementName = "Address")]
        public string HexAddress
        {
            get { return "0x" + Address.ToString("X"); }
            set
            {
                Address = uint.Parse(value, System.Globalization.NumberStyles.HexNumber);
            }
        }

        public string Name;

        public short Size;
        public bool Signed;
        public decimal Resolution;

        public decimal MinValue;
        public decimal MaxValue;
        public string Unit;
        public string Description;

        public string Category;


        [XmlIgnore]
        public bool Parsed = false;
    }

    public static class Variables
    {
        public static List<Variable> variables = new List<Variable>();
        static Variables()
        {
            Variable categoryVar = null;
            foreach (Variable v in parsedVariables)
            {
                Variable cat = variables.FirstOrDefault(f => f.Address == v.Address);
                if (cat != null)
                {
                    variables.Remove(cat);
                    categoryVar = cat;
                }
                if (categoryVar != null)
                {
                    v.Category = $"{categoryVar.Name} - {categoryVar.Description}";
                }
                variables.Add(v);
            }
        }

        private static List<Variable> parsedVariables = new List<Variable>()
        {
            new Variable() {Address = 0x20A1, Name = "UMV-EMS", Description="Unified measured values for EMS" },
            new Variable() {Address = 0x20A1, Name = "TOIL"},
            new Variable() {Address = 0x20A2, Name = "STATE_PUMP_OIL_CTL_MVB"},
            new Variable() {Address = 0x20A3, Name = "STATE_POIL_SWI_MVB"},
            new Variable() {Address = 0x20A4, Name = "STATE_MIS_ACT_DC"},
            new Variable() {Address = 0x2029, Name = "MAP_SP"},
            new Variable() {Address = 0x2682, Name = "STATE_VLV_HEAT_TM"},
            new Variable() {Address = 0x2981, Name = "RFP_SP"},
            new Variable() {Address = 0x2982, Name = "RFP_AV"},
            new Variable() {Address = 0x2983, Name = "RFP_AD_STOP"},
            new Variable() {Address = 0x2984, Name = "VP_RFP_AD_BOL_1"},
            new Variable() {Address = 0x2985, Name = "RFP_AD_STEP_CTR"},
            new Variable() {Address = 0x29C8, Name = "V_PORT_1_RAW"},
            new Variable() {Address = 0x29C9, Name = "V_PORT_2_RAW"},
            new Variable() {Address = 0x20FE, Name = "STATE_EOL_CPS"},
            new Variable() {Address = 0x296D, Name = "STATE_EVAP_SYS_EOL"},
            new Variable() {Address = 0x296A, Name = "LV_DIAG_SMT_SWI_AV_NVLD"},
            new Variable() {Address = 0x3D51, Name = "TAM_SMT_NVLD"},
            new Variable() {Address = 0x392A, Name = "TCYLH_OUT_TM"},
            new Variable() {Address = 0x3D73, Name = "PWM_CWP_MAIN_TM"},
            new Variable() {Address = 0x3D74, Name = "LV_VLV_GB_HEAT_OPEN_TM"},
            new Variable() {Address = 0x3DB1, Name = "LV_VLV_GB_COOL_OPEN_TM"},

            new Variable() {Address = 0x2069, Name = "AIRM", Description="Air Motion UID"},
            new Variable() {Address = 0x2069, Name = "LV_PORT_DEAC"},
            new Variable() {Address = 0x206A, Name = "FAC_PORT_DEAC[0]"},
            new Variable() {Address = 0x206B, Name = "LV_PORT_DEAC"},
            new Variable() {Address = 0x206C, Name = "FAC_PORT_DEAC[1]"},
            new Variable() {Address = 0x20B2, Name = "V_PORT_1_OFS"},
            new Variable() {Address = 0x20B4, Name = "V_PORT_2_OFS"},

            new Variable() {Address = 0x1000, Name = "AIRT", Description = "Air Temperature" },
            new Variable() {Address = 0x1000, Name = "TAM"},
            new Variable() {Address = 0x1001, Name = "TIA"},
            new Variable() {Address = 0x1002, Name = "TIA_MES[NC_IDX_TIA_IM_CYL]"},
            new Variable() {Address = 0x1003, Name = "TIA_MES[NC_IDX_TIA_AM_SCHA]"},
            new Variable() {Address = 0x1004, Name = "TIA_MES[NC_IDX_TIA_IM_CYL_1]"},
            new Variable() {Address = 0x1005, Name = "TIA_MES[NC_IDX_TIA_IM_CYL_2]"},
            new Variable() {Address = 0x1006, Name = "TIA[NC_IDX_TIA_AM_SCHA]"},
            new Variable() {Address = 0x1007, Name = "TIA[NC_IDX_TIA_IM_CYL_1]"},
            new Variable() {Address = 0x1008, Name = "TIA[NC_IDX_TIA_IM_CYL_2]"},
            new Variable() {Address = 0x101E, Name = "COMR", Description = "Communication realization" },
            new Variable() {Address = 0x101E, Name = "ECF_REQ_AC_CAN"},
            new Variable() {Address = 0x1020, Name = "TQ_ACC_CAN"},
            new Variable() {Address = 0x1021, Name = "TQI_ASR_REQ_FAST"},
            new Variable() {Address = 0x1022, Name = "TQI_GS_FAST_DEC"},
            new Variable() {Address = 0x1023, Name = "TQI_GS_FAST_INC"},
            new Variable() {Address = 0x1024, Name = "GEN_LOAD_POW_CAN"},
            new Variable() {Address = 0x1025, Name = "MAX_HLD_ACU"},
            new Variable() {Address = 0x1026, Name = "MAX_HLD_BEM"},
            new Variable() {Address = 0x1027, Name = "MAX_HLD_CCU"},
            new Variable() {Address = 0x1028, Name = "MAX_HLD_DCC"},
            new Variable() {Address = 0x1029, Name = "MAX_HLD_EILU"},
            new Variable() {Address = 0x102A, Name = "MAX_HLD_EPB"},
            new Variable() {Address = 0x102B, Name = "MAX_HLD_FTL_SENS"},
            new Variable() {Address = 0x102C, Name = "MAX_HLD_ICH"},
            new Variable() {Address = 0x102D, Name = "MAX_HLD_ICL"},
            new Variable() {Address = 0x102E, Name = "MAX_HLD_IF_CFT"},
            new Variable() {Address = 0x102F, Name = "MAX_HLD_LAMP_RE"},
            new Variable() {Address = 0x1030, Name = "MAX_HLD_PSTE"},
            new Variable() {Address = 0x1031, Name = "MAX_HLD_SCU"},
            new Variable() {Address = 0x1032, Name = "MAX_HLD_SMLS"},
            new Variable() {Address = 0x1033, Name = "MAX_HLD_TCU"},
            new Variable() {Address = 0x1034, Name = "MAX_HLD_TCS"},
            new Variable() {Address = 0x1035, Name = "MAX_HLD_TRLCU"},
            new Variable() {Address = 0x1036, Name = "LF_STATE_CAN_SYS_MVB"},
            new Variable() {Address = 0x1040, Name = "CYBL / CILC", Description = "Cylinder Balancing"},
            new Variable() {Address = 0x1040, Name = "MFF_ADD_L_CUR_LAM_CYL_SEL_ADJ[0]"},
            new Variable() {Address = 0x1041, Name = "MFF_ADD_L_CUR_LAM_CYL_SEL_ADJ[1]"},
            new Variable() {Address = 0x1042, Name = "MFF_ADD_L_CUR_LAM_CYL_SEL_ADJ[2]"},
            new Variable() {Address = 0x1043, Name = "MFF_ADD_L_CUR_LAM_CYL_SEL_ADJ[3]"},
            new Variable() {Address = 0x1044, Name = "MFF_ADD_L_CUR_LAM_CYL_SEL_ADJ[4]"},
            new Variable() {Address = 0x1045, Name = "MFF_ADD_L_CUR_LAM_CYL_SEL_ADJ[5]"},
            new Variable() {Address = 0x1046, Name = "DELTA_CRK_CYL_LAM_1"},
            new Variable() {Address = 0x1047, Name = "DELTA_CRK_CYL_LAM_2"},
            new Variable() {Address = 0x1048, Name = "MFF_ADD_LAM_CYL_SEL_ADJ_H_RES[0]"},
            new Variable() {Address = 0x1049, Name = "MFF_ADD_LAM_CYL_SEL_ADJ_H_RES[1]"},
            new Variable() {Address = 0x104A, Name = "MFF_ADD_LAM_CYL_SEL_ADJ_H_RES[2]"},
            new Variable() {Address = 0x104B, Name = "MFF_ADD_LAM_CYL_SEL_ADJ_H_RES[3]"},
            new Variable() {Address = 0x104C, Name = "MFF_ADD_LAM_CYL_SEL_ADJ_H_RES[4]"},
            new Variable() {Address = 0x104D, Name = "MFF_ADD_LAM_CYL_SEL_ADJ_H_RES[5]"},
            new Variable() {Address = 0x104E, Name = "MFF_ADD_H_CUR_LAM_CYL_SEL_ADJ[0]"},
            new Variable() {Address = 0x104F, Name = "MFF_ADD_H_CUR_LAM_CYL_SEL_ADJ[1]"},
            new Variable() {Address = 0x1050, Name = "MFF_ADD_H_CUR_LAM_CYL_SEL_ADJ[2]"},
            new Variable() {Address = 0x1051, Name = "MFF_ADD_H_CUR_LAM_CYL_SEL_ADJ[3]"},
            new Variable() {Address = 0x1052, Name = "MFF_ADD_H_CUR_LAM_CYL_SEL_ADJ[4]"},
            new Variable() {Address = 0x1053, Name = "MFF_ADD_H_CUR_LAM_CYL_SEL_ADJ[5]"},
            new Variable() {Address = 0x1055, Name = "CHRG", Description = "Charger"},
            new Variable() {Address = 0x1055, Name = "VP_RFP_1"},
            new Variable() {Address = 0x1057, Name = "VP_RFP_BOL_1"},
            new Variable() {Address = 0x1058, Name = "VP_RFP_AD_LIH_1"},
            new Variable() {Address = 0x1059, Name = "VP_RFP_LIH_1"},
            new Variable() {Address = 0x105A, Name = "RFPPWM"},
            new Variable() {Address = 0x105F, Name = "LV_RFP_AD_EXT_ADJ_ON"},
            new Variable() {Address = 0x1060, Name = "N_CWP_2"},
            new Variable() {Address = 0x1061, Name = "STATE_CWP_2"},
            new Variable() {Address = 0x1062, Name = "STATE_CWP_2_ACR_TEST"},
            new Variable() {Address = 0x1063, Name = "VP_RFP_BOL_MTC_1"},
            new Variable() {Address = 0x1064, Name = "RFP_AD_STOP_SAVE"},
            new Variable() {Address = 0x1065, Name = "LV_RFP_CUR_OFF"},
            new Variable() {Address = 0x1066, Name = "LV_RFP_POS_GRD"},
            new Variable() {Address = 0x1067, Name = "T_RAMP_RFP_SP_OSC"},
            new Variable() {Address = 0x106E, Name = "DRRQ", Description = "Driver request"},
            new Variable() {Address = 0x106E, Name = "V_PVS_1"},
            new Variable() {Address = 0x106F, Name = "V_PVS_2"},
            new Variable() {Address = 0x1070, Name = "PV_AV"},
            new Variable() {Address = 0x1071, Name = "PV_AV_H"},
            new Variable() {Address = 0x1072, Name = "PV_AV_1"},
            new Variable() {Address = 0x1073, Name = "PV_AV_2"},
            new Variable() {Address = 0x1074, Name = "LV_KD"},
            new Variable() {Address = 0x1075, Name = "V_PVS_MAX"},
            new Variable() {Address = 0x1090, Name = "ECOP", Description="Engine operating"},
            new Variable() {Address = 0x1090, Name = "DIST_ENG_RUN_IN"},
            new Variable() {Address = 0x1091, Name = "LV_ENG_RUN_IN"},
            new Variable() {Address = 0x1092, Name = "LV_ENG_RUN_IN_EXT_ADJ"},
            new Variable() {Address = 0x1096, Name = "EGCP", Description="Engine gas composition"},
            new Variable() {Address = 0x1096, Name = "FAC_MV_DIAG_DYN_LSL_UP[1]"},
            new Variable() {Address = 0x1097, Name = "FAC_MV_DIAG_DYN_LSL_UP[2]"},
            new Variable() {Address = 0x1098, Name = "LAMB_LS_UP[1]"},
            new Variable() {Address = 0x1099, Name = "LAMB_LS_UP[2]"},
            new Variable() {Address = 0x109A, Name = "LAM_CYL_SEL_ADJ_FAC[0]"},
            new Variable() {Address = 0x109B, Name = "LAM_CYL_SEL_ADJ_FAC[1]"},
            new Variable() {Address = 0x109C, Name = "LAM_CYL_SEL_ADJ_FAC[2]"},
            new Variable() {Address = 0x109D, Name = "LAM_CYL_SEL_ADJ_FAC[3]"},
            new Variable() {Address = 0x109E, Name = "LAM_CYL_SEL_ADJ_FAC[4]"},
            new Variable() {Address = 0x109F, Name = "LAM_CYL_SEL_ADJ_FAC[5]"},
            new Variable() {Address = 0x10A0, Name = "R_IT_LS_DOWN[1]"},
            new Variable() {Address = 0x10A1, Name = "R_IT_LS_DOWN[2]"},
            new Variable() {Address = 0x10A2, Name = "R_IT_LS_UP[1]"},
            new Variable() {Address = 0x10A3, Name = "R_IT_LS_UP[2]"},
            new Variable() {Address = 0x10A4, Name = "VLS_DOWN[1]"},
            new Variable() {Address = 0x10A5, Name = "VLS_DOWN[2]"},
            new Variable() {Address = 0x10A6, Name = "VLS_UP[1]"},
            new Variable() {Address = 0x10A7, Name = "VLS_UP[2]"},
            new Variable() {Address = 0x10A8, Name = "VLS_UP_DIAG_SAVE_PUC_L"},
            new Variable() {Address = 0x10A9, Name = "VLS_UP_DIAG_SAVE_PUC_L"},
            new Variable() {Address = 0x10AA, Name = "LV_LAM_ADJ_I_ACT[1]"},
            new Variable() {Address = 0x10AB, Name = "LV_LAM_ADJ_I_ACT[2]"},
            new Variable() {Address = 0x10AC, Name = "LV_LS_DOWN_READY[1]"},
            new Variable() {Address = 0x10AD, Name = "LV_LS_DOWN_READY[2]"},
            new Variable() {Address = 0x10AE, Name = "LV_INH_LSH_DOWN[1]"},
            new Variable() {Address = 0x10AF, Name = "LV_INH_LSH_DOWN[2]"},
            new Variable() {Address = 0x10B0, Name = "LV_LAM_ADJ_P_ACT[1]"},
            new Variable() {Address = 0x10B1, Name = "LV_LAM_ADJ_P_ACT[2]"},
            new Variable() {Address = 0x10B2, Name = "LV_LAM_LSCL[1]"},
            new Variable() {Address = 0x10B3, Name = "LV_LAM_LSCL[2]"},
            new Variable() {Address = 0x10B4, Name = "LV_LAM_STOP[1]"},
            new Variable() {Address = 0x10B5, Name = "LV_LAM_STOP[2]"},
            new Variable() {Address = 0x10B6, Name = "LV_LS_UP_READY[1]"},
            new Variable() {Address = 0x10B7, Name = "LV_LS_UP_READY[2]"},
            new Variable() {Address = 0x10B8, Name = "LV_INH_LSH_UP[1]"},
            new Variable() {Address = 0x10B9, Name = "LV_INH_LSH_UP[2]"},
            new Variable() {Address = 0x10BA, Name = "LV_CAT_PURGE_ACT[1]"},
            new Variable() {Address = 0x10BB, Name = "LV_CAT_PURGE_ACT[2]"},
            new Variable() {Address = 0x10BE, Name = "EGTR", Description="Exhaust gas treatment system"},
            new Variable() {Address = 0x10BE, Name = "EFF_CAT_DIAG[1]"},
            new Variable() {Address = 0x10BF, Name = "EFF_CAT_DIAG[2]"},
            new Variable() {Address = 0x10C0, Name = "RATIO_MASS_O2_CAT_DIF[1]"},
            new Variable() {Address = 0x10C1, Name = "RATIO_MASS_O2_CAT_DIF[2]"},
            new Variable() {Address = 0x10C2, Name = "LAMB_CAT_DOWN_MV[1]"},
            new Variable() {Address = 0x10C3, Name = "LAMB_CAT_DOWN_MV[2]"},
            new Variable() {Address = 0x10C4, Name = "CTR_CAT_DIAG[1]"},
            new Variable() {Address = 0x10C5, Name = "CTR_CAT_DIAG[2]"},
            new Variable() {Address = 0x10C6, Name = "O2L_1_MAX_BAS_AD_CAT[1]"},
            new Variable() {Address = 0x10C7, Name = "O2L_1_MAX_BAS_AD_CAT[2]"},
            new Variable() {Address = 0x10C8, Name = "O2L_1_MAX_BAS_AD_CAT_DIAG[1]"},
            new Variable() {Address = 0x10C9, Name = "O2L_1_MAX_BAS_AD_CAT_DIAG[2]"},
            new Variable() {Address = 0x10E6, Name = "ENLU", Description="Engine lubrication"},
            new Variable() {Address = 0x10E6, Name = "TOIL_SRV_INTL"},
            new Variable() {Address = 0x10E7, Name = "WEAR_FCO_EQU"},
            new Variable() {Address = 0x10E8, Name = "LV_PUMP_OIL_EL_SP"},
            new Variable() {Address = 0x10EA, Name = "LV_POIL_SWI_L"},
            new Variable() {Address = 0x10EB, Name = "LV_POIL_SWI_H"},
            new Variable() {Address = 0x10EC, Name = "LOIL_SRV_INTL"},
            new Variable() {Address = 0x10ED, Name = "LOIL_COR_SRV_INTL_DYN"},
            new Variable() {Address = 0x10EE, Name = "LOIL_MIN_SRV_INTL"},
            new Variable() {Address = 0x10EF, Name = "LOIL_MAX_SRV_INTL"},
            new Variable() {Address = 0x10F0, Name = "LV_CAN_HOOD_SWI"},
            new Variable() {Address = 0x10F1, Name = "LV_LOIL_L_WARN_TMP"},
            new Variable() {Address = 0x10F2, Name = "LV_LOIL_L_WARN"},
            new Variable() {Address = 0x10F3, Name = "LOIL_DYN"},
            new Variable() {Address = 0x10F4, Name = "T_COOL_LOIL"},
            new Variable() {Address = 0x10F5, Name = "T_TEMP_SIG_LOIL"},
            new Variable() {Address = 0x10F6, Name = "CTR_SUM_SRV_INTL"},
            new Variable() {Address = 0x10F7, Name = "LOIL_SUM_SRV_INTL"},
            new Variable() {Address = 0x10F8, Name = "LOIL_DYN_TMP"},
            new Variable() {Address = 0x10F9, Name = "LV_LOIL_L_WARN_ACT"},
            new Variable() {Address = 0x110E, Name = "ENOS", Description="Engine operating states"},
            new Variable() {Address = 0x110E, Name = "STATE_ENG"},
            new Variable() {Address = 0x112C, Name = "ENRD", Description ="Engine roughness determination"},
            new Variable() {Address = 0x112C, Name = "SEG_AD_MMV_ER[0]"},
            new Variable() {Address = 0x112D, Name = "SEG_AD_MMV_ER[1]"},
            new Variable() {Address = 0x112E, Name = "SEG_AD_MMV_ER[2]"},
            new Variable() {Address = 0x112F, Name = "SEG_AD_MMV_ER[3]"},
            new Variable() {Address = 0x1130, Name = "SEG_AD_MMV_ER[4]"},
            new Variable() {Address = 0x1131, Name = "SEG_AD_MMV_ER[5]"},
            new Variable() {Address = 0x1132, Name = "SEG_AD_MMV_ER_MID[0]"},
            new Variable() {Address = 0x1133, Name = "SEG_AD_MMV_ER_MID[1]"},
            new Variable() {Address = 0x1134, Name = "SEG_AD_MMV_ER_MID[2]"},
            new Variable() {Address = 0x1135, Name = "SEG_AD_MMV_ER_MID[3]"},
            new Variable() {Address = 0x1136, Name = "SEG_AD_MMV_ER_MID[4]"},
            new Variable() {Address = 0x1137, Name = "SEG_AD_MMV_ER_MID[5]"},
            new Variable() {Address = 0x1138, Name = "SEG_AD_MMV_ER_H[0]"},
            new Variable() {Address = 0x1139, Name = "SEG_AD_MMV_ER_H[1]"},
            new Variable() {Address = 0x113A, Name = "SEG_AD_MMV_ER_H[2]"},
            new Variable() {Address = 0x113B, Name = "SEG_AD_MMV_ER_H[3]"},
            new Variable() {Address = 0x113C, Name = "SEG_AD_MMV_ER_H[4]"},
            new Variable() {Address = 0x113D, Name = "SEG_AD_MMV_ER_H[5]"},
            new Variable() {Address = 0x113E, Name = "SEG_AD_MMV_ER_L[0]"},
            new Variable() {Address = 0x113F, Name = "SEG_AD_MMV_ER_L[1]"},
            new Variable() {Address = 0x1140, Name = "SEG_AD_MMV_ER_L[2]"},
            new Variable() {Address = 0x1141, Name = "SEG_AD_MMV_ER_L[3]"},
            new Variable() {Address = 0x1142, Name = "SEG_AD_MMV_ER_L[4]"},
            new Variable() {Address = 0x1143, Name = "SEG_AD_MMV_ER_L[5]"},
            new Variable() {Address = 0x1154, Name = "ENSC", Description="Engine speed control"},
            new Variable() {Address = 0x1154, Name = "N_SP_IS"},
            new Variable() {Address = 0x1155, Name = "TQ_DIF_I_IS"},
            new Variable() {Address = 0x117C, Name = "ENSD", Description="Engine position and speed determination"},
            new Variable() {Address = 0x117C, Name = "N"},
            new Variable() {Address = 0x117D, Name = "N_32"},
            new Variable() {Address = 0x117E, Name = "PSN_EDGE_1_AD_CAM_IN_1"},
            new Variable() {Address = 0x117F, Name = "PSN_EDGE_2_AD_CAM_IN_1"},
            new Variable() {Address = 0x1180, Name = "PSN_EDGE_1_AD_CAM_EX_1"},
            new Variable() {Address = 0x1181, Name = "PSN_EDGE_2_AD_CAM_EX_1"},
            new Variable() {Address = 0x1182, Name = "LV_AD_END_IVVT"},
            new Variable() {Address = 0x1183, Name = "PSN_AD_CAM_EX_1"},
            new Variable() {Address = 0x1184, Name = "PSN_AD_CAM_EX_2"},
            new Variable() {Address = 0x1185, Name = "PSN_AD_CAM_IN_1"},
            new Variable() {Address = 0x1186, Name = "PSN_AD_CAM_IN_2"},
            new Variable() {Address = 0x1187, Name = "ENSS", Description="Engine start and stop"},
            new Variable() {Address = 0x1187, Name = "N_CAM_32_DIAG_CRK_SIG_LOSS"},
            new Variable() {Address = 0x1188, Name = "N_TOOTH_32_DIAG_CRK_SIG_LOSS"},
            new Variable() {Address = 0x11A4, Name = "LV_ST_REQ"},
            new Variable() {Address = 0x11A5, Name = "LV_ST_RESP"},
            new Variable() {Address = 0x11A6, Name = "LV_STR_1"},
            new Variable() {Address = 0x11A7, Name = "LV_STR_2"},
            new Variable() {Address = 0x11A8, Name = "T_AST"},
            new Variable() {Address = 0x11A9, Name = "LV_INH_AUT_ST"},
            new Variable() {Address = 0x11AA, Name = "LV_INH_STR_RLY"},
            new Variable() {Address = 0x392D, Name = "LF_STATE_STST_STOP_INH_EMS"},
            new Variable() {Address = 0x392E, Name = "LF_STATE_STST_ST_REQ_EMS"},
            new Variable() {Address = 0x392F, Name = "STATE_STST_MNG_SYS"},
            new Variable() {Address = 0x3930, Name = "LF_STATE_STST_ST_REQ_ECU"},
            new Variable() {Address = 0x3931, Name = "LF_STATE_STST_STOP_INH_ECU"},
            new Variable() {Address = 0x3932, Name = "LF_STATE_STST_ERR_ECU"},
            new Variable() {Address = 0x3933, Name = "LF_STATE_STST_ERR_SENS"},
            new Variable() {Address = 0x11CC, Name = "ENTE", Description="Engine temperature"},
            new Variable() {Address = 0x11CA, Name = "LV_CWP_ACT"},
            new Variable() {Address = 0x11CB, Name = "LV_VAR_CWP"},
            new Variable() {Address = 0x11CC, Name = "ECFPWM_1"},
            new Variable() {Address = 0x11CD, Name = "ECFPWM_2"},
            new Variable() {Address = 0x11CE, Name = "T_POP_COC_INTER_1"},
            new Variable() {Address = 0x11CF, Name = "TCO"},
            new Variable() {Address = 0x11D0, Name = "TCO_1_2"},
            new Variable() {Address = 0x11D1, Name = "TCO_RAW_1"},
            new Variable() {Address = 0x11D2, Name = "TCO_SP"},
            new Variable() {Address = 0x11D3, Name = "TCO_ST"},
            new Variable() {Address = 0x11D4, Name = "STATE_ECF_POW_AD_1"},
            new Variable() {Address = 0x11D5, Name = "STATE_ECF_POW_AD_2"},
            new Variable() {Address = 0x11D6, Name = "PWM_CWP_2"},
            new Variable() {Address = 0x11D7, Name = "TCYLH"},
            new Variable() {Address = 0x11D8, Name = "ERRM", Description="Error management"},
            new Variable() {Address = 0x11D8, Name = "STATE_READY_OBD_1"},
            new Variable() {Address = 0x11D9, Name = "STATE_READY_OBD_2"},
            new Variable() {Address = 0x11DA, Name = "STATE_READY_OBD_3"},
            new Variable() {Address = 0x11DB, Name = "TPS_ENVD"},
            new Variable() {Address = 0x11DC, Name = "MAF_ENVD"},
            new Variable() {Address = 0x11DD, Name = "FUP_ENVD"},
            new Variable() {Address = 0x11DE, Name = "T_AST_ENVD"},
            new Variable() {Address = 0x11DF, Name = "FUP_EFP_ENVD"},
            new Variable() {Address = 0x11E0, Name = "AMP_ENVD"},
            new Variable() {Address = 0x11E1, Name = "AMP_AD_ENVD"},
            new Variable() {Address = 0x11E2, Name = "CTR_VLFT_STND_SWI_NOT_ENVD[0]"},
            new Variable() {Address = 0x11E3, Name = "CTR_VLFT_STND_SWI_NOT_ENVD[1]"},
            new Variable() {Address = 0x11E4, Name = "CTR_VLFT_STND_SWI_NOT_ENVD[2]"},
            new Variable() {Address = 0x11E5, Name = "CTR_VLFT_STND_SWI_NOT_ENVD[3]"},
            new Variable() {Address = 0x11E6, Name = "CTR_VLFT_STND_SWI_NOT_ENVD[4]"},
            new Variable() {Address = 0x11E7, Name = "CTR_VLFT_STND_SWI_NOT_ENVD[5]"},
            new Variable() {Address = 0x11E8, Name = "CTR_VLFT_1_SWI_NOT_ENVD[0]"},
            new Variable() {Address = 0x11E9, Name = "CTR_VLFT_1_SWI_NOT_ENVD[1]"},
            new Variable() {Address = 0x11EA, Name = "CTR_VLFT_1_SWI_NOT_ENVD[2]"},
            new Variable() {Address = 0x11EB, Name = "CTR_VLFT_1_SWI_NOT_ENVD[3]"},
            new Variable() {Address = 0x11EC, Name = "CTR_VLFT_1_SWI_NOT_ENVD[4]"},
            new Variable() {Address = 0x11ED, Name = "CTR_VLFT_1_SWI_NOT_ENVD[5]"},
            new Variable() {Address = 0x11EE, Name = "CTR_VVL_SWI_L_ENVD"},
            new Variable() {Address = 0x11EF, Name = "ENVD_EEPROM"},
            new Variable() {Address = 0x11F2, Name = "FUEL_MASS_AD_ENVD"},
            new Variable() {Address = 0x11F3, Name = "FUEL_MASS_REQ_I_CTL_ENVD"},
            new Variable() {Address = 0x11F4, Name = "DIAG_INST[0]"},
            new Variable() {Address = 0x11F5, Name = "DIAG_INST[1]"},
            new Variable() {Address = 0x11F6, Name = "DIAG_INST[2]"},
            new Variable() {Address = 0x11F7, Name = "DIAG_INST[3]"},
            new Variable() {Address = 0x11F8, Name = "DIAG_INST[4]"},
            new Variable() {Address = 0x11F9, Name = "DIAG_INST[5]"},
            new Variable() {Address = 0x11FA, Name = "DIAG_INST[6]"},
            new Variable() {Address = 0x11FB, Name = "DIAG_INST[7]"},
            new Variable() {Address = 0x11FC, Name = "DIAG_INST[8]"},
            new Variable() {Address = 0x11FD, Name = "DIAG_INST[9]"},
            new Variable() {Address = 0x11FE, Name = "DIST_ACT_MIL"},
            new Variable() {Address = 0x11FF, Name = "DIST_DTC_CLR"},
            new Variable() {Address = 0x1200, Name = "LOAD_CLC"},
            new Variable() {Address = 0x1201, Name = "T_ACT_MIL"},
            new Variable() {Address = 0x1202, Name = "T_DTC_CLR"},
            new Variable() {Address = 0x1203, Name = "STATE_LS_ENVD[1]"},
            new Variable() {Address = 0x1204, Name = "STATE_LS_ENVD[2]"},
            new Variable() {Address = 0x1205, Name = "MAP_ENVD"},
            new Variable() {Address = 0x1206, Name = "V_TPS_1_ENVD"},
            new Variable() {Address = 0x1207, Name = "V_TPS_2_ENVD"},
            new Variable() {Address = 0x1208, Name = "V_PVS_1_ENVD"},
            new Variable() {Address = 0x1209, Name = "V_PVS_2_ENVD"},
            new Variable() {Address = 0x120A, Name = "TEMP_CAT_ENVD[1]"},
            new Variable() {Address = 0x120B, Name = "TEMP_CAT_ENVD[2]"},
            new Variable() {Address = 0x120C, Name = "VLS_UP_1_ENVD"},
            new Variable() {Address = 0x120D, Name = "VLS_UP_2_ENVD"},
            new Variable() {Address = 0x120E, Name = "VLS_DOWN_1_ENVD"},
            new Variable() {Address = 0x120F, Name = "VLS_DOWN_2_ENVD"},
            new Variable() {Address = 0x1210, Name = "TQI_AV_ENVD"},
            new Variable() {Address = 0x1211, Name = "V_PORT_1_ENVD"},
            new Variable() {Address = 0x1212, Name = "V_PORT_2_ENVD"},
            new Variable() {Address = 0x1213, Name = "ENVD_CAM_IN_1"},
            new Variable() {Address = 0x1214, Name = "ENVD_CAM_IN_2"},
            new Variable() {Address = 0x1215, Name = "ENVD_CAM_EX_1"},
            new Variable() {Address = 0x1216, Name = "ENVD_CAM_EX_2"},
            new Variable() {Address = 0x1217, Name = "ENVD_LSL_UP_1"},
            new Variable() {Address = 0x1218, Name = "ENVD_LSL_UP_2"},
            new Variable() {Address = 0x1219, Name = "ENVD_CRK"},
            new Variable() {Address = 0x121A, Name = "ENVD_KNK_RTD_LIM"},
            new Variable() {Address = 0x121C, Name = "RBM", Description="Rate Based Monitoring"},
            new Variable() {Address = 0x121C, Name = "CTR_KM_CAN"},
            new Variable() {Address = 0x121D, Name = "NC_NR_DIAG_RBM"},
            new Variable() {Address = 0x121E, Name = "CTR_CDN_OBD_RBM"},
            new Variable() {Address = 0x121F, Name = "CTR_IGK_CYC_RBM"},
            new Variable() {Address = 0x1220, Name = "CTR_CDN_RBM_CAT_1"},
            new Variable() {Address = 0x1221, Name = "CTR_CDN_RBM_CAT_2"},
            new Variable() {Address = 0x1222, Name = "CTR_COMP_RBM_CAT_1"},
            new Variable() {Address = 0x1223, Name = "CTR_COMP_RBM_CAT_2"},
            new Variable() {Address = 0x1244, Name = "EVAC", Description="Evaporative system control"},
            new Variable() {Address = 0x1244, Name = "CPPWM_CPS"},
            new Variable() {Address = 0x1245, Name = "CL_MMV"},
            new Variable() {Address = 0x1246, Name = "FLOW_CPS"},
            new Variable() {Address = 0x1247, Name = "FAC_LAM_CP"},
            new Variable() {Address = 0x126C, Name = "EVAM", Description="Evaporative system monitoring"},
            new Variable() {Address = 0x126C, Name = "STATE_REQ_NVLD"},
            new Variable() {Address = 0x126D, Name = "STATE_NVLD"},
            new Variable() {Address = 0x126E, Name = "STATE_COMC_NVLD"},
            new Variable() {Address = 0x1294, Name = "EXTD", Description="Exhaust system temperature determination"},
            new Variable() {Address = 0x1294, Name = "TEG_DYN_UP_CAT[1]"},
            new Variable() {Address = 0x1295, Name = "TEG_DYN_UP_CAT[2]"},
            new Variable() {Address = 0x1296, Name = "TEG_DYN_DOWN_CAT[1]"},
            new Variable() {Address = 0x1297, Name = "TEG_DYN_DOWN_CAT[2]"},
            new Variable() {Address = 0x1298, Name = "TEMP_CAT_DYN_MDL[1]"},
            new Variable() {Address = 0x1299, Name = "TEMP_CAT_DYN_MDL[2]"},
            new Variable() {Address = 0x129A, Name = "TEMP_CAT_STAT_MDL[1]"},
            new Variable() {Address = 0x129B, Name = "TEMP_CAT_STAT_MDL[2]"},
            new Variable() {Address = 0x12BC, Name = "FCTM", Description="Function management"},
            new Variable() {Address = 0x12BC, Name = "T_PWL"},
            new Variable() {Address = 0x12BD, Name = "PWL_LOCK_CDN"},
            new Variable() {Address = 0x12E4, Name = "FMSP", Description="Fuel mass setpoint"},
            new Variable() {Address = 0x12E4, Name = "FCO_SUM"},
            new Variable() {Address = 0x12E5, Name = "FAC_FQ_ST_AD_SAVE_RNG_1"},
            new Variable() {Address = 0x12E6, Name = "FAC_FQ_ST_AD_SAVE_RNG_2"},
            new Variable() {Address = 0x12E7, Name = "FAC_FQ_ST_AD_SAVE_RNG_3"},
            new Variable() {Address = 0x130C, Name = "FUSL", Description="Fuel supply"},
            new Variable() {Address = 0x130C, Name = "FUEL_MASS_AD"},
            new Variable() {Address = 0x130D, Name = "FUEL_MASS_REQ_I_CTL"},
            new Variable() {Address = 0x130E, Name = "FUP"},
            new Variable() {Address = 0x130F, Name = "FUP_SP"},
            new Variable() {Address = 0x1310, Name = "PUMP_VOL_VCV"},
            new Variable() {Address = 0x1311, Name = "FUP_DIF"},
            new Variable() {Address = 0x1312, Name = "FUEL_MASS_REQ_P_CTL"},
            new Variable() {Address = 0x1313, Name = "STATE_VCV"},
            new Variable() {Address = 0x1314, Name = "MAF_KGH_MV"},
            new Variable() {Address = 0x1315, Name = "MAF_KGH_INT"},
            new Variable() {Address = 0x1316, Name = "MAF_KGH_INT_THD_DIAG_TH"},
            new Variable() {Address = 0x1317, Name = "TCO_DIAG_TH"},
            new Variable() {Address = 0x1318, Name = "VS_MV_DIAG_TH"},
            new Variable() {Address = 0x1319, Name = "T_FAC_MAF_MAX_ORNG"},
            new Variable() {Address = 0x131A, Name = "T_INT_DIAG_TH"},
            new Variable() {Address = 0x131B, Name = "VCV_CLOSE_RNG"},
            new Variable() {Address = 0x131C, Name = "EFPPWM"},
            new Variable() {Address = 0x131D, Name = "LV_EFPPWM_AD_STOP"},
            new Variable() {Address = 0x131E, Name = "EFPPWM_MIN_AD"},
            new Variable() {Address = 0x131F, Name = "EFPPWM_I"},
            new Variable() {Address = 0x1320, Name = "EFPPWM_I_AD"},
            new Variable() {Address = 0x1321, Name = "FUP_EFP"},
            new Variable() {Address = 0x1322, Name = "FUP_EFP_ST_H"},
            new Variable() {Address = 0x1323, Name = "FUP_EFP_ST_L"},
            new Variable() {Address = 0x1324, Name = "FUP_EFP_STOP_H"},
            new Variable() {Address = 0x1325, Name = "FUP_EFP_STOP_L"},
            new Variable() {Address = 0x1326, Name = "V_FUP_EFP_MV"},
            new Variable() {Address = 0x1327, Name = "T_EFP"},
            new Variable() {Address = 0x1328, Name = "T_EFP_MEM_H"},
            new Variable() {Address = 0x1329, Name = "T_EFP_MEM_L"},
            new Variable() {Address = 0x132B, Name = "LV_VCV_RLY"},
            new Variable() {Address = 0x132C, Name = "FUP_H"},
            new Variable() {Address = 0x133E, Name = "FUTL", Description="Fuel tank level"},
            new Variable() {Address = 0x133E, Name = "LV_FRS"},
            new Variable() {Address = 0x135C, Name = "ENVD", Description="Environmental data"},
            new Variable() {Address = 0x1353, Name = "VP_RFP_1_ENVD"},
            new Variable() {Address = 0x1354, Name = "VP_RFP_AD_BOL_1_ENVD"},
            new Variable() {Address = 0x1355, Name = "VP_RFP_AD_LIH_1_ENVD"},
            new Variable() {Address = 0x1356, Name = "VP_RFP_BOL_MTC_1_ENVD"},
            new Variable() {Address = 0x1357, Name = "RFPPWM_ENVD"},
            new Variable() {Address = 0x1358, Name = "RFP_SP_ENVD"},
            new Variable() {Address = 0x1359, Name = "RFP_AV_ENVD"},
            new Variable() {Address = 0x135A, Name = "RFP_AD_STOP_SAVE_LOW_ENDV"},
            new Variable() {Address = 0x135B, Name = "RFP_AD_STOP_SAVE_HIGH_ENDV"},
            new Variable() {Address = 0x135C, Name = "HVAC", Description="Heating, Ventilation and Air Conditioning"},
            new Variable() {Address = 0x135C, Name = "TQ_LOSS_ACC"},
            new Variable() {Address = 0x135D, Name = "LV_ACCIN_ON"},
            new Variable() {Address = 0x135E, Name = "LV_ACC_RED_CMD"},
            new Variable() {Address = 0x135F, Name = "LV_ACIN"},
            new Variable() {Address = 0x137A, Name = "IGSP", Description ="Ignition angle setpoint"},
            new Variable() {Address = 0x137A, Name = "IGA_AV_MV"},
            new Variable() {Address = 0x138A, Name = "IGRE", Description="Ignition realization"},
            new Variable() {Address = 0x138A, Name = "IGA_IGC[0]"},
            new Variable() {Address = 0x138B, Name = "IGA_IGC[1]"},
            new Variable() {Address = 0x138C, Name = "IGA_IGC[2]"},
            new Variable() {Address = 0x138D, Name = "IGA_IGC[3]"},
            new Variable() {Address = 0x138E, Name = "IGA_IGC[4]"},
            new Variable() {Address = 0x138F, Name = "IGA_IGC[5]"},
            new Variable() {Address = 0x13A2, Name = "INJR", Description="Injection realization"},
            new Variable() {Address = 0x13A2, Name = "LV_FCUT_IND"},
            new Variable() {Address = 0x13A3, Name = "TI_1_HOM[1]"},
            new Variable() {Address = 0x13A4, Name = "TI_1_HOM[2]"},
            new Variable() {Address = 0x13A5, Name = "TI_1_HOM[0]"},
            new Variable() {Address = 0x13A6, Name = "TI_1_HOM[3]"},
            new Variable() {Address = 0x13A7, Name = "TI_1_HOM[4]"},
            new Variable() {Address = 0x13A8, Name = "TI_1_HOM[5]"},
            new Variable() {Address = 0x13A9, Name = "TI_2_HOM[0]"},
            new Variable() {Address = 0x13AA, Name = "TI_2_HOM[1]"},
            new Variable() {Address = 0x13AB, Name = "TI_2_HOM[2]"},
            new Variable() {Address = 0x13AC, Name = "TI_2_HOM[3]"},
            new Variable() {Address = 0x13AD, Name = "TI_2_HOM[4]"},
            new Variable() {Address = 0x13AE, Name = "TI_2_HOM[5]"},
            new Variable() {Address = 0x13B0, Name = "IMMO", Description="Immobilizer"},
            new Variable() {Address = 0x13B0, Name = "FRF_IMMO_SNAPSHOT_BYTE1"},
            new Variable() {Address = 0x13B1, Name = "FRF_IMMO_SNAPSHOT_BYTE2"},
            new Variable() {Address = 0x13B2, Name = "FRF_IMMO_SNAPSHOT_BYTE3"},
            new Variable() {Address = 0x13B3, Name = "FRF_IMMO_SNAPSHOT_BYTE4"},
            new Variable() {Address = 0x13B4, Name = "FRF_IMMO_SNAPSHOT_BYTE5"},
            new Variable() {Address = 0x13B5, Name = "FRF_IMMO_SNAPSHOT_BYTE6"},
            new Variable() {Address = 0x13CA, Name = "INSY", Description="Intake system"},
            new Variable() {Address = 0x13CA, Name = "AMP"},
            new Variable() {Address = 0x13CB, Name = "AMP_MES"},
            new Variable() {Address = 0x13CC, Name = "AR_RED_DIF_I_REL"},
            new Variable() {Address = 0x13CD, Name = "MAF_KGH"},
            new Variable() {Address = 0x13CE, Name = "MAF_THR"},
            new Variable() {Address = 0x13CF, Name = "FAC_MAF_MAX"},
            new Variable() {Address = 0x13D0, Name = "MAP"},
            new Variable() {Address = 0x13D1, Name = "MAP_MES"},
            new Variable() {Address = 0x13D2, Name = "MAP_MES_BAS"},
            new Variable() {Address = 0x13D3, Name = "AR_RED_AD_ADD_MMV"},
            new Variable() {Address = 0x13D4, Name = "AR_RED_AD_FAC"},
            new Variable() {Address = 0x13D5, Name = "CAM_PHA_OFS_MAF[IN][1]"},
            new Variable() {Address = 0x13D6, Name = "CAM_PHA_OFS_MAF[IN][2]"},
            new Variable() {Address = 0x13D7, Name = "CAM_OFS_IVVT_IN[1]"},
            new Variable() {Address = 0x13D8, Name = "CAM_OFS_IVVT_IN[2]"},
            new Variable() {Address = 0x13D9, Name = "FAC_SLOP_IV[1]"},
            new Variable() {Address = 0x13DA, Name = "FAC_SLOP_IV[2]"},
            new Variable() {Address = 0x13DB, Name = "MAF_DIF_CAM_OFS_AD_SQ"},
            new Variable() {Address = 0x13DC, Name = "MAP_1_MES"},
            new Variable() {Address = 0x13DD, Name = "MAP_2_MES"},
            new Variable() {Address = 0x13DE, Name = "PDT_MES"},
            new Variable() {Address = 0x13DF, Name = "MAF_CYL"},
            new Variable() {Address = 0x13E0, Name = "MAF"},
            new Variable() {Address = 0x13E1, Name = "MAF_SCHA"},
            new Variable() {Address = 0x13E2, Name = "MAF_RFP"},
            new Variable() {Address = 0x13E3, Name = "PDT_ENVD"},
            new Variable() {Address = 0x13E4, Name = "MAP_1_ENVD"},
            new Variable() {Address = 0x13E5, Name = "MAP_2_ENVD"},
            new Variable() {Address = 0x13E6, Name = "MAP_1_MES_BAS"},
            new Variable() {Address = 0x13E7, Name = "MAP_2_MES_BAS"},
            new Variable() {Address = 0x13E8, Name = "PDT_MES_BAS"},
            new Variable() {Address = 0x13F2, Name = "KNCK", Description="Knock"},
            new Variable() {Address = 0x13F2, Name = "IGA_ADJ_KNK[0]"},
            new Variable() {Address = 0x13F3, Name = "IGA_ADJ_KNK[1]"},
            new Variable() {Address = 0x13F4, Name = "IGA_ADJ_KNK[2]"},
            new Variable() {Address = 0x13F5, Name = "IGA_ADJ_KNK[3]"},
            new Variable() {Address = 0x13F6, Name = "IGA_ADJ_KNK[4]"},
            new Variable() {Address = 0x13F7, Name = "IGA_ADJ_KNK[5]"},
            new Variable() {Address = 0x13F8, Name = "NL[0]"},
            new Variable() {Address = 0x13F9, Name = "NL[1]"},
            new Variable() {Address = 0x13FA, Name = "NL[2]"},
            new Variable() {Address = 0x13FB, Name = "NL[3]"},
            new Variable() {Address = 0x13FC, Name = "NL[4]"},
            new Variable() {Address = 0x13FD, Name = "NL[5]"},
            new Variable() {Address = 0x141A, Name = "LACO", Description="Lambda control"},
            new Variable() {Address = 0x141A, Name = "FAC_LAM_AD[1]"},
            new Variable() {Address = 0x141B, Name = "FAC_LAM_AD[2]"},
            new Variable() {Address = 0x141C, Name = "FAC_LAM_LIM[1]"},
            new Variable() {Address = 0x141D, Name = "FAC_LAM_LIM[2]"},
            new Variable() {Address = 0x141E, Name = "FAC_LAM_MV_MMV[1]"},
            new Variable() {Address = 0x141F, Name = "FAC_LAM_MV_MMV[2]"},
            new Variable() {Address = 0x1420, Name = "FAC_LAM_OUT[1]"},
            new Variable() {Address = 0x1421, Name = "FAC_LAM_OUT[2]"},
            new Variable() {Address = 0x1422, Name = "FAC_MFF_ADD_LAM_AD_OUT[1]"},
            new Variable() {Address = 0x1423, Name = "FAC_MFF_ADD_LAM_AD_OUT[2]"},
            new Variable() {Address = 0x1424, Name = "LAMB_DELTA_LAM_ADJ[1]"},
            new Variable() {Address = 0x1425, Name = "LAMB_DELTA_LAM_ADJ[2]"},
            new Variable() {Address = 0x1426, Name = "LAMB_DELTA_AD_LAM_ADJ[1]"},
            new Variable() {Address = 0x1427, Name = "LAMB_DELTA_AD_LAM_ADJ[2]"},
            new Variable() {Address = 0x1428, Name = "FAC_LAM_TCO_A[1]"},
            new Variable() {Address = 0x1429, Name = "FAC_LAM_TCO_A[2]"},
            new Variable() {Address = 0x142A, Name = "FAC_LAM_TCO_B[1]"},
            new Variable() {Address = 0x142B, Name = "FAC_LAM_TCO_B[2]"},
            new Variable() {Address = 0x142C, Name = "FAC_LAM_TCO_C[1]"},
            new Variable() {Address = 0x142D, Name = "FAC_LAM_TCO_C[2]"},
            new Variable() {Address = 0x142E, Name = "FAC_LAM_TCO_D[1]"},
            new Variable() {Address = 0x142F, Name = "FAC_LAM_TCO_D[2]"},
            new Variable() {Address = 0x1430, Name = "FAC_LAM_TCO_E[1]"},
            new Variable() {Address = 0x1431, Name = "FAC_LAM_TCO_E[2]"},
            new Variable() {Address = 0x1432, Name = "TCO_MIN_LAM_AD_WUP[1]"},
            new Variable() {Address = 0x1433, Name = "TCO_MIN_LAM_AD_WUP[2]"},
            new Variable() {Address = 0x1434, Name = "TCO_MIN_INTER_LAM_AD_"},
            new Variable() {Address = 0x1435, Name = "TCO_MIN_INTER_LAM_AD_"},
            new Variable() {Address = 0x1436, Name = "TCO_A_LAM_AD_WUP[1]"},
            new Variable() {Address = 0x1437, Name = "TCO_A_LAM_AD_WUP[2]"},
            new Variable() {Address = 0x1438, Name = "TCO_B_LAM_AD_WUP[1]"},
            new Variable() {Address = 0x1439, Name = "TCO_B_LAM_AD_WUP[2]"},
            new Variable() {Address = 0x143A, Name = "TCO_C_LAM_AD_WUP[1]"},
            new Variable() {Address = 0x143B, Name = "TCO_C_LAM_AD_WUP[2]"},
            new Variable() {Address = 0x143C, Name = "TCO_D_LAM_AD_WUP[1]"},
            new Variable() {Address = 0x143D, Name = "TCO_D_LAM_AD_WUP[2]"},
            new Variable() {Address = 0x143E, Name = "TCO_E_LAM_AD_WUP[1]"},
            new Variable() {Address = 0x143F, Name = "TCO_E_LAM_AD_WUP[2]"},
            new Variable() {Address = 0x1440, Name = "FAC_L_RNG_LAM_AD[1]"},
            new Variable() {Address = 0x1441, Name = "FAC_L_RNG_LAM_AD[2]"},
            new Variable() {Address = 0x1442, Name = "FAC_H_RNG_LAM_AD[1]"},
            new Variable() {Address = 0x1443, Name = "FAC_H_RNG_LAM_AD[2]"},
            new Variable() {Address = 0x1444, Name = "MFF_ADD_LAM_AD[1]"},
            new Variable() {Address = 0x1445, Name = "MFF_ADD_LAM_AD[2]"},
            new Variable() {Address = 0x1446, Name = "LAMB_DELTA_AD_O2L_CAT[1]"},
            new Variable() {Address = 0x1447, Name = "LAMB_DELTA_AD_O2L_CAT[2]"},
            new Variable() {Address = 0x1456, Name = "LASP", Description="Lambda setpoint"},
            new Variable() {Address = 0x1456, Name = "LAMB_SP_BAS[1]"},
            new Variable() {Address = 0x1457, Name = "LAMB_SP_BAS[2]"},
            new Variable() {Address = 0x1458, Name = "LAMB_SP[1]"},
            new Variable() {Address = 0x1459, Name = "LAMB_SP[2]"},
            new Variable() {Address = 0x147E, Name = "MISF", Description="Misfire monitoring"},
            new Variable() {Address = 0x147E, Name = "CTR_MIS_DC_CYL[0]"},
            new Variable() {Address = 0x147F, Name = "CTR_MIS_DC_CYL[1]"},
            new Variable() {Address = 0x1480, Name = "CTR_MIS_DC_CYL[2]"},
            new Variable() {Address = 0x1481, Name = "CTR_MIS_DC_CYL[3]"},
            new Variable() {Address = 0x1482, Name = "CTR_MIS_DC_CYL[4]"},
            new Variable() {Address = 0x1483, Name = "CTR_MIS_DC_CYL[5]"},
            new Variable() {Address = 0x1484, Name = "MIS_CTR_B[0]"},
            new Variable() {Address = 0x1485, Name = "MIS_CTR_B[1]"},
            new Variable() {Address = 0x1486, Name = "MIS_CTR_B[2]"},
            new Variable() {Address = 0x1487, Name = "MIS_CTR_B[3]"},
            new Variable() {Address = 0x1488, Name = "MIS_CTR_B[4]"},
            new Variable() {Address = 0x1489, Name = "MIS_CTR_B[5]"},
            new Variable() {Address = 0x148A, Name = "LV_REQ_INH_MIS"},
            new Variable() {Address = 0x148B, Name = "MIS_SUM_B"},
            new Variable() {Address = 0x148C, Name = "CTR_MIS_TOT_NVMY"},
            new Variable() {Address = 0x148D, Name = "CTR_MIS_DC_MMV_CYL[0]"},
            new Variable() {Address = 0x148E, Name = "CTR_MIS_DC_MMV_CYL[1]"},
            new Variable() {Address = 0x148F, Name = "CTR_MIS_DC_MMV_CYL[2]"},
            new Variable() {Address = 0x1490, Name = "CTR_MIS_DC_MMV_CYL[3]"},
            new Variable() {Address = 0x1491, Name = "CTR_MIS_DC_MMV_CYL[4]"},
            new Variable() {Address = 0x1492, Name = "CTR_MIS_DC_MMV_CYL[5]"},
            new Variable() {Address = 0x14A6, Name = "PWSL", Description="Power supply"},
            new Variable() {Address = 0x14A6, Name = "VB"},
            new Variable() {Address = 0x14C4, Name = "SAIR", Description="Secondary air"},
            new Variable() {Address = 0x14C4, Name = "PRS_SA_DIF"},
            new Variable() {Address = 0x14C5, Name = "MASS_SA_REL[0]"},
            new Variable() {Address = 0x14C6, Name = "MASS_SA_REL[1]"},
            new Variable() {Address = 0x14C7, Name = "MASS_SA_REL_PHA_1[0]"},
            new Variable() {Address = 0x14C8, Name = "MASS_SA_REL_PHA_1[1]"},
            new Variable() {Address = 0x14C9, Name = "MASS_SA_REL_PHA_2[0]"},
            new Variable() {Address = 0x14CA, Name = "MASS_SA_REL_PHA_2[1]"},
            new Variable() {Address = 0x14CB, Name = "MASS_SA_REL_21_PHA"},
            new Variable() {Address = 0x14CC, Name = "MASS_SA_REL_22_PHA"},
            new Variable() {Address = 0x14CD, Name = "LV_MASS_SA_L_ERR[0]"},
            new Variable() {Address = 0x14CE, Name = "LV_MASS_SA_L_ERR[1]"},
            new Variable() {Address = 0x14CF, Name = "LV_SA_SYS_END_DIAG[0]"},
            new Variable() {Address = 0x14D0, Name = "LV_SA_SYS_END_DIAG[1]"},
            new Variable() {Address = 0x14D1, Name = "LV_SA_MAX_H_ERR[0]"},
            new Variable() {Address = 0x14D2, Name = "LV_SA_MAX_H_ERR[1]"},
            new Variable() {Address = 0x14D3, Name = "LV_SA_SAV_END_DIAG[0]"},
            new Variable() {Address = 0x14D4, Name = "LV_SA_SAV_END_DIAG[1]"},
            new Variable() {Address = 0x14EC, Name = "SYCF", Description= "System configuration"},
            new Variable() {Address = 0x14EC, Name = "CPU_LOAD"},
            new Variable() {Address = 0x150A, Name = "THRO", Description="Throttle"},
            new Variable() {Address = 0x150A, Name = "MTCPWM"},
            new Variable() {Address = 0x150B, Name = "TPS_AD_STEP"},
            new Variable() {Address = 0x150C, Name = "TPS_AV"},
            new Variable() {Address = 0x150D, Name = "V_TPS_1"},
            new Variable() {Address = 0x150E, Name = "V_TPS_2"},
            new Variable() {Address = 0x150F, Name = "V_TPS_AD_EL_BOL_1"},
            new Variable() {Address = 0x1510, Name = "V_TPS_AD_EL_BOL_2"},
            new Variable() {Address = 0x1511, Name = "V_TPS_AD_LIH_1"},
            new Variable() {Address = 0x1512, Name = "V_TPS_AD_LIH_2"},
            new Variable() {Address = 0x1513, Name = "LV_TPS_AD_ACT"},
            new Variable() {Address = 0x1514, Name = "LV_TPS_AD_REQ"},
            new Variable() {Address = 0x1515, Name = "LV_TPS_AD_DIAG_ERR"},
            new Variable() {Address = 0x1516, Name = "TPS_AD_CDN_MISS"},
            new Variable() {Address = 0x1532, Name = "TLDP", Description="Tank Leakage Detection Pump"},
            new Variable() {Address = 0x1532, Name = "LV_RS_TLDP"},
            new Variable() {Address = 0x1533, Name = "STATE_TLDP"},
            new Variable() {Address = 0x1534, Name = "LV_ERR_EVAP_LEAK"},
            new Variable() {Address = 0x1535, Name = "ERR_SYM_EVAP_LEAK"},
            new Variable() {Address = 0x155A, Name = "TQDR", Description ="Torque determination and realization"},
            new Variable() {Address = 0x155A, Name = "TQI_AV"},
            new Variable() {Address = 0x155B, Name = "EFF_IGA_CST_QUO_IS_MAX"},
            new Variable() {Address = 0x155C, Name = "EFF_IGA_CST_QUO_PL_MAX"},
            new Variable() {Address = 0x1582, Name = "TQLO"},
            new Variable() {Address = 0x1582, Name = "TQ_LOSS", Description="Torque losses"},
            new Variable() {Address = 0x1583, Name = "TQ_DIF_IS_AD"},
            new Variable() {Address = 0x1584, Name = "TQ_DIF_IS_AD_ACC"},
            new Variable() {Address = 0x15AA, Name = "TRSM", Description="Transmission"},
            new Variable() {Address = 0x15AA, Name = "GEAR"},
            new Variable() {Address = 0x15AB, Name = "LV_GS_REQ"},
            new Variable() {Address = 0x15AC, Name = "TQ_CONV"},
            new Variable() {Address = 0x15AD, Name = "LV_DRI"},
            new Variable() {Address = 0x15D2, Name = "VHMD", Description="Vehicle motion determination"},
            new Variable() {Address = 0x15D2, Name = "VS"},
            new Variable() {Address = 0x15D3, Name = "VS_FIL"},
            new Variable() {Address = 0x15D4, Name = "DIST_ST"},
            new Variable() {Address = 0x15FA, Name = "VHSC", Description="Vehicle speed control"},
            new Variable() {Address = 0x15FA, Name = "STATE_CRU_CTL"},
            new Variable() {Address = 0x15FB, Name = "LV_CRU_ENA"},
            new Variable() {Address = 0x15FC, Name = "LV_DCC_ENA"},
            new Variable() {Address = 0x15FD, Name = "CRU_SWI_POS"},
            new Variable() {Address = 0x15FE, Name = "LV_PIN_CRU_SWI"},
            new Variable() {Address = 0x15FF, Name = "VS_SP_CRU"},
            new Variable() {Address = 0x1600, Name = "CRU_SWI_POS_CAN"},
            new Variable() {Address = 0x1601, Name = "LF_STATE_DEAC_CRU_IRV"},
            new Variable() {Address = 0x1602, Name = "LF_STATE_DEAC_CRU_RV"},
            new Variable() {Address = 0x1603, Name = "LF_CRU_OFF_BRAKE_INTV_I"},
            new Variable() {Address = 0x1604, Name = "LF_CRU_OFF_BRAKE_INTV_"},
            new Variable() {Address = 0x1622, Name = "VHST", Description="Vehicle stability and traction"},
            new Variable() {Address = 0x1622, Name = "LV_ASR_ACT"},
            new Variable() {Address = 0x164A, Name = "VIMA", Description="Variable Intake Manifold"},
            new Variable() {Address = 0x164A, Name = "LV_IAF_SP"},
            new Variable() {Address = 0x164B, Name = "LV_VIM_SP"},
            new Variable() {Address = 0x164C, Name = "V_VIM"},
            new Variable() {Address = 0x164D, Name = "VIM_AV_MMV"},
            new Variable() {Address = 0x164E, Name = "VIM_SP_MMV"},
            new Variable() {Address = 0x164F, Name = "V_VIM_AD_SHO"},
            new Variable() {Address = 0x1650, Name = "V_VIM_AD_LONG"},
            new Variable() {Address = 0x1651, Name = "STATE_VIM_AD"},
            new Variable() {Address = 0x1652, Name = "V_VIM_SHO"},
            new Variable() {Address = 0x1653, Name = "V_VIM_LONG"},
            new Variable() {Address = 0x1672, Name = "VVLI", Description="Variable Valve Lift"},
            new Variable() {Address = 0x1672, Name = "LF_VLFT_1_SWI_NOT"},
            new Variable() {Address = 0x1673, Name = "LF_VLFT_STND_SWI_NOT"},
            new Variable() {Address = 0x1675, Name = "CTR_VVL_SWI_DC"},
            new Variable() {Address = 0x1677, Name = "LF_VVL_DIAG_SWI_NOT"},
            new Variable() {Address = 0x1678, Name = "CTR_VVL_SWI_L"},
            new Variable() {Address = 0x1679, Name = "CTR_VVL_SWI_H"},
            new Variable() {Address = 0x167A, Name = "CTR_VVL_LIH_DEAC"},
            new Variable() {Address = 0x167B, Name = "NR_CYL_VVL_H_ACK"},
            new Variable() {Address = 0x167C, Name = "STATE_VVL_MNG"},
            new Variable() {Address = 0x167D, Name = "STATE_VVL_CTL"},
            new Variable() {Address = 0x167E, Name = "CTR_VLFT_1_SWI_NOT[0]"},
            new Variable() {Address = 0x167F, Name = "CTR_VLFT_1_SWI_NOT[1]"},
            new Variable() {Address = 0x1680, Name = "CTR_VLFT_1_SWI_NOT[2]"},
            new Variable() {Address = 0x1681, Name = "CTR_VLFT_1_SWI_NOT[3]"},
            new Variable() {Address = 0x1682, Name = "CTR_VLFT_1_SWI_NOT[4]"},
            new Variable() {Address = 0x1683, Name = "CTR_VLFT_1_SWI_NOT[5]"},
            new Variable() {Address = 0x1684, Name = "CTR_VLFT_STND_SWI_NOT[0]"},
            new Variable() {Address = 0x1685, Name = "CTR_VLFT_STND_SWI_NOT[1]"},
            new Variable() {Address = 0x1686, Name = "CTR_VLFT_STND_SWI_NOT[2]"},
            new Variable() {Address = 0x1687, Name = "CTR_VLFT_STND_SWI_NOT[3]"},
            new Variable() {Address = 0x1688, Name = "CTR_VLFT_STND_SWI_NOT[4]"},
            new Variable() {Address = 0x1689, Name = "CTR_VLFT_STND_SWI_NOT[5]"},
            new Variable() {Address = 0x168A, Name = "LV_ERR_VLFT_1_SWI[0]"},
            new Variable() {Address = 0x168B, Name = "LV_ERR_VLFT_1_SWI[1]"},
            new Variable() {Address = 0x168C, Name = "LV_ERR_VLFT_1_SWI[2]"},
            new Variable() {Address = 0x168D, Name = "LV_ERR_VLFT_1_SWI[3]"},
            new Variable() {Address = 0x168E, Name = "LV_ERR_VLFT_1_SWI[4]"},
            new Variable() {Address = 0x168F, Name = "LV_ERR_VLFT_1_SWI[5]"},
            new Variable() {Address = 0x1690, Name = "LV_ERR_VLFT_STND_SWI[0]"},
            new Variable() {Address = 0x1691, Name = "LV_ERR_VLFT_STND_SWI[1]"},
            new Variable() {Address = 0x1692, Name = "LV_ERR_VLFT_STND_SWI[2]"},
            new Variable() {Address = 0x1693, Name = "LV_ERR_VLFT_STND_SWI[3]"},
            new Variable() {Address = 0x1694, Name = "LV_ERR_VLFT_STND_SWI[4]"},
            new Variable() {Address = 0x1695, Name = "LV_ERR_VLFT_STND_SWI[5]"},
            new Variable() {Address = 0x16A4, Name = "VVTI", Description="Variable Valve Timing"},
            new Variable() {Address = 0x16A4, Name = "IVVTPWM_EX[1]"},
            new Variable() {Address = 0x16A5, Name = "IVVTPWM_EX[2]"},
            new Variable() {Address = 0x16A6, Name = "IVVTPWM_IN[1]"},
            new Variable() {Address = 0x16A7, Name = "IVVTPWM_IN[2]"},
            new Variable() {Address = 0x16A8, Name = "CAM_PHA[EX][1]"},
            new Variable() {Address = 0x16A9, Name = "CAM_PHA[EX][2]"},
            new Variable() {Address = 0x16AA, Name = "CAM_PHA[IN][1]"},
            new Variable() {Address = 0x16AB, Name = "CAM_PHA[IN][2]"},
            new Variable() {Address = 0x16AC, Name = "CAM_SP_IVVT_IN"},
            new Variable() {Address = 0x16AD, Name = "CAM_SP_IVVT_EX"},
            new Variable() {Address = 0x16AE, Name = "C_CAM_INI_IN"},
            new Variable() {Address = 0x16AF, Name = "C_CAM_INI_EX"},
            new Variable() {Address = 0x16CC, Name = "MISC", Description="Misc."},
            new Variable() {Address = 0x16CC, Name = "LV_CLU_SWI"},
            new Variable() {Address = 0x16CD, Name = "LV_CLU_SWI_2"},
            new Variable() {Address = 0x16CE, Name = "LV_BLS"},
            new Variable() {Address = 0x16CF, Name = "LV_BTS"},
            new Variable() {Address = 0x16D0, Name = "LV_AEB_ACT_1"},
            new Variable() {Address = 0x16D1, Name = "LV_AEB_ACT_2"},
            new Variable() {Address = 0x16D2, Name = "LV_ATB_ACT_1"},
            new Variable() {Address = 0x16D3, Name = "LV_ATB_ACT_2"},
            new Variable() {Address = 0x16D4, Name = "STATE_READY_DIAG_86_1"},
            new Variable() {Address = 0x16D5, Name = "STATE_END_DIAG_86_2"},
            new Variable() {Address = 0x16D6, Name = "STATE_END_DIAG_86_3"},
            new Variable() {Address = 0x16D7, Name = "STATE_END_DIAG_86_4"},
            new Variable() {Address = 0x16D8, Name = "STATE_ERR_DIAG_87_2"},
            new Variable() {Address = 0x16D9, Name = "STATE_ERR_DIAG_87_3"},
            new Variable() {Address = 0x16DA, Name = "STATE_ERR_DIAG_87_4"},
            new Variable() {Address = 0x16DB, Name = "STATE_END_DIAG_88_1"},
            new Variable() {Address = 0x16DC, Name = "STATE_END_DIAG_88_2"},
            new Variable() {Address = 0x16DD, Name = "STATE_END_DIAG_88_3"},
            new Variable() {Address = 0x16DE, Name = "AS"},
            new Variable() {Address = 0x16DF, Name = "STATE_SW_MVB[0...15]"},
            new Variable() {Address = 0x16F0, Name = "ECM2", Description="ECU Process Monitoring"},
            new Variable() {Address = 0x16F0, Name = "ENVD_0_MON"},
            new Variable() {Address = 0x16F1, Name = "ENVD_1_MON"},
            new Variable() {Address = 0x16F2, Name = "ENVD_2_MON"},
            new Variable() {Address = 0x16F3, Name = "ENVD_3_MON"},
            new Variable() {Address = 0x16F4, Name = "ENVD_0_TQI_MON"},
            new Variable() {Address = 0x16F5, Name = "ENVD_1_TQI_MON"},
            new Variable() {Address = 0x16F6, Name = "ENVD_2_TQI_MON"},
            new Variable() {Address = 0x16F7, Name = "ENVD_3_TQI_MON"},
            new Variable() {Address = 0x16F8, Name = "ENVD_0_N_MAX_MON"},
            new Variable() {Address = 0x16F9, Name = "ENVD_1_N_MAX_MON"},
            new Variable() {Address = 0x16FA, Name = "ENVD_2_N_MAX_MON"},
            new Variable() {Address = 0x16FB, Name = "ENVD_3_N_MAX_MON"},
            new Variable() {Address = 0x16FC, Name = "ENVD_0_CRU_ACT_MON"},
            new Variable() {Address = 0x16FD, Name = "ENVD_1_CRU_ACT_MON"},
            new Variable() {Address = 0x16FE, Name = "ENVD_2_CRU_ACT_MON"},
            new Variable() {Address = 0x16FF, Name = "ENVD_3_CRU_ACT_MON"},
            new Variable() {Address = 0x1700, Name = "ENVD_0_MSR_MON"},
            new Variable() {Address = 0x1701, Name = "ENVD_1_MSR_MON"},
            new Variable() {Address = 0x1702, Name = "ENVD_2_MSR_MON"},
            new Variable() {Address = 0x1703, Name = "ENVD_3_MSR_MON"},
            new Variable() {Address = 0x1704, Name = "ENVD_0_GS_INC_MON"},
            new Variable() {Address = 0x1705, Name = "ENVD_1_GS_INC_MON"},
            new Variable() {Address = 0x1706, Name = "ENVD_2_GS_INC_MON"},
            new Variable() {Address = 0x1707, Name = "ENVD_3_GS_INC_MON"},
            new Variable() {Address = 0x1708, Name = "ENVD_0_MAF_NOT_PLAUS_MON"},
            new Variable() {Address = 0x1709, Name = "ENVD_1_MAF_NOT_PLAUS_MON"},
            new Variable() {Address = 0x170A, Name = "ENVD_2_MAF_NOT_PLAUS_MON"},
            new Variable() {Address = 0x170B, Name = "ENVD_3_MAF_NOT_PLAUS_MON"},
            new Variable() {Address = 0x1710, Name = "ECM3", Description="MC processor monitoring"},
            new Variable() {Address = 0x1710, Name = "ENVD_0_MON_3"},
            new Variable() {Address = 0x1711, Name = "ENVD_1_MON_3"},
            new Variable() {Address = 0x1712, Name = "ENVD_2_MON_3"},
            new Variable() {Address = 0x1713, Name = "ENVD_3_MON_3"},
            new Variable() {Address = 0x3972, Name = "EXTC", Description="Exhaust temperature control"},
            new Variable() {Address = 0x3972, Name = "LV_EF"},
        };
    }
}
